userName=input("Enter your user name: ")
fullName=input("Enter your full name: ")
course=input("Enter your course: ")
city=input("Enter your city: ")
age=int(input("Enter your age: "))
print("User Profile:")
print("User Name:", userName)
print("Full Name:", fullName)
print("Course:", course)
print("City:", city)
print("Age:", age)